// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CM.FoldDocComments
{
    internal sealed partial class Vsix
    {
        public const string Id = "CM.FoldDocComments.5be8d5f3-b006-4128-b342-54ed6658aeef";
        public const string Name = "CM.FoldDocComments";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Chaplin Marchais";
        public const string Tags = "";
    }
}
