// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CM.FoldDocComments
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string FoldDocCommentsString = "8df83ae3-4b19-42c9-9e22-7bef4f9eeee1";
        public static Guid FoldDocComments = new Guid(FoldDocCommentsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CmMenuGroup = 0x0001;
        public const int FoldDocCommentsCommand = 0x0100;
    }
}