// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CM.FoldDocComments
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string FoldDocCommentsCmdSetString = "8df83ae3-4b19-42c9-9e22-7bef4f9eeee1";
        public static Guid FoldDocCommentsCmdSet = new Guid(FoldDocCommentsCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FoldDocCommentsCmdGrp = 0x0205;
        public const int EditorContextGrp = 0x0204;
        public const int MainMenuEditGrp = 0x0205;
        public const int CollapseDocCommentsCommand = 0x0102;
    }
}